import { addHours, toLocalInputValue } from './format.js';

export function createInitialState(options = {}) {
  return {
  tables: [],
  players: [],
  members: [],
  staff: [],
  games: [],
  gameRecommendations: [],
  tableRecommendations: [],
  reservations: [],
  openSessions: [],
  leaderboard: [],
  leaderboardSort: 'winrate',
  publicRentalGames: [],
  popularity: [],
  tableUtilization: [],
  revenue: null,
  maintenance: null,
  venue: null,
  memberReservations: [],
  memberReservationMemberId: null,
  memberReservationsLoading: false,
  selectedId: null,
  selectedMemberId: null,
  selectedStaffId: null,
  activePage: options.activePage || 'customer',
  sidebarCollapsed: !!options.sidebarCollapsed,
  mobileNavOpen: false,
  petOpen: false,
  petMessages: [],
  petInput: '',
  petLoading: false,
  authToken: options.authToken || '',
  currentUser: null,
  customerToken: options.customerToken || '',
  customerPlayer: null,
  customerAuthMode: 'login',
  customerLoginPhone: '',
  customerLoginPassword: '',
  customerRegisterName: '',
  customerRegisterPhone: '',
  customerRegisterPassword: '',
  customerReservations: [],
  customerReservationsLoading: false,
  customerRecordReservationId: null,
  customerRecordGameId: '',
  customerRecordWinnerMode: 'self',
  customerRecordWinnerName: '',
  customerRecordScore: '',
  authMode: 'login',
  loginUsername: 'admin',
  loginPassword: '',
  registerUsername: '',
  registerDisplayName: '',
  registerPassword: '',
  health: '正在连接',
  mode: 'loading',
  err: '',
  guestName: '访客',
  guestPhone: '',
  playerId: '',
  partySize: 4,
  startAt: toLocalInputValue(new Date()),
  endAt: toLocalInputValue(addHours(new Date(), 2)),
  tableMatchUpdatedAt: '',
  billedMin: 90,
  amountYuan: '48',
  settleNotes: '',
  memberSearch: '',
  staffSearch: '',
  gameSearch: '',
  newMemberName: '',
  newMemberPhone: '',
  newMemberBalance: '100',
  memberAmount: '100',
  newStaffName: '',
  newStaffPhone: '',
  newStaffPosition: '店员',
  editStaffName: '',
  editStaffPhone: '',
  editStaffPosition: '',
  staffAccountUsername: '',
  staffAccountPassword: '',
  staffAccountRole: 'staff',
  recommendPlayerId: '',
  recommendPartySize: 4,
  recommendMinutes: 120,
  recommendCategory: '',
  recommendationUpdatedAt: '',
  customerGuestName: '',
  customerPhone: '',
  customerPartySize: 4,
  customerStartAt: toLocalInputValue(addHours(new Date(), 1)),
  customerEndAt: toLocalInputValue(addHours(new Date(), 3)),
  customerSelectedTableId: '',
  customerMatches: [],
  customerResult: null,
  customerCatalogExpanded: false,
  rentalTab: 'active',
  rentalLoanGameId: '',
  rentalLoanCopyId: '',
  rentalLoanPlayerId: '',
  rentalLoanDueAt: options.rentalLoanDueAt || '',
  rentalLoanDeposit: '50',
  rentalNewCopyGameId: '',
  rentalNewCopyBarcode: '',
  rentalNewCopyLocation: '',
  rentalNewCopyDeposit: '50',
  aiMessages: [],
  aiInput: '',
  aiLoading: false,
  custChatOpen: false,
  custChatMessages: [],
  custChatInput: '',
  custChatLoading: false,
  aiSnapshot: null,
  aiCards: [],
  aiActions: [],
  aiToolResults: [],
  customerGuideGames: [],
  customerGuideTables: [],
};
}
